# Setup
title:               Machine Learning
tagline:             'A Jekyll theme'
description:         
url:                 
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sindhuja
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
